/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

class AppTest {
    @Test void app_has_built() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.testBuild(), "app should show a build success message");
    }
}
