/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import javax.swing.JFrame;

import main.java.org.SortingMethods;

public class App extends JFrame {
    final canvas canvas = new canvas();
    
    public App() {
        setVisible(true);
        setTitle("Sorting Visualization");
        setMinimumSize(canvas.getSize());
        add(canvas);
        pack();
    }

    public String test_build() {
        return "build is successful";
    }

    public static void main(String[] args) {
        System.out.println(new App().test_build());

        SortingMethods.selectionSort(new int[]{2, 4, 5, 3, 2, 6, 3, 6, 1, 2});
    }
}
